CREATE database Street_db;

USE Street_db;
CREATE TABLE reviews (
	id INTEGER AUTO_INCREMENT NOT NULL,
	PRIMARY KEY (id),

	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)

USE travelApp_db;
CREATE TABLE reviews (
	id INTEGER AUTO_INCREMENT NOT NULL,
	PRIMARY KEY (id),
	review VARCHAR(255) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)

